// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLogLevel } from "./AppLogLevel.js";
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type AppLogEvent = {
  /**
   * Unix timestamp (seconds).
   */
  ts: bigint;
  level: AppLogLevel;
  /**
   * Stable event type slug, e.g. "credential.circuit.opened".
   */
  event_type: string;
  /**
   * Versioned event payload. Renderers must prefer this snapshot over live DB rows.
   */
  payload: JsonValue;
  /**
   * Short category slug: "provider", "credential", "circuit", "system", …
   */
  category: string;
  /**
   * Legacy fallback message for old rows or unknown event renderers.
   */
  message: string;
  detail: string | null;
};
