// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientStatus = {
  client: string;
  config_path: string;
  config_exists: boolean;
  taken_over: boolean;
  expected_base_url: string;
  configured_base_url: string | null;
  auth_proxy_managed: boolean | null;
  model_overrides_present: Array<string>;
  notes: Array<string>;
};
