// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientStatus } from "./ClientStatus";

export type ClientTakeoverResult = {
  client: string;
  config_path: string;
  backup_path: string | null;
  status: ClientStatus;
};
