// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary returned by Codex history preview/apply endpoints.
 */
export type CodexHistorySummary = {
  codex_home: string;
  provider: string;
  from_providers: Array<string>;
  applied: boolean;
  sqlite_files_seen: number;
  sqlite_files_changed: number;
  sqlite_rows_changed: number;
  rollout_files_seen: number;
  rollout_files_changed: number;
  rollout_fields_changed: number;
  backups_created: number;
};
