// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexAppStatus } from "./CodexAppStatus.js";

export type CodexAppActionResult = { action: string; status: CodexAppStatus };
