// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialVendor } from "./CredentialVendor.js";

/**
 * Body for `POST /_vp/providers/:id/credentials` and `PUT /_vp/credentials/:id`.
 *
 * Set either `auth_ref` (points to a secret) **or** `oauth_access_token` +
 * `oauth_refresh_token` (stored directly in SQLite).  Do not set both.
 */
export type CredentialInput = {
  label: string;
  auth_ref: string | null;
  plan_type: string | null;
  notes: string | null;
  enabled: boolean;
  priority: number;
  oauth_access_token: string | null;
  /**
   * Write-only: stored in DB but never returned in Credential responses.
   */
  oauth_refresh_token: string | null;
  oauth_expires_at: bigint | null;
  /**
   * From Codex `id_token` at import; persisted and merged into Credential `oauth_account_*` for UI.
   */
  oauth_cached_email: string | null;
  oauth_cached_subject: string | null;
  oauth_cached_plan_slug: string | null;
  upstream_vendor: CredentialVendor | null;
  upstream_username: string | null;
  /**
   * Set to Some to store a new session token; leave None to preserve existing.
   */
  upstream_session: string | null;
  upstream_session_expires_at: bigint | null;
  upstream_group: string | null;
  /**
   * Cost multiplier relative to official pricing (default 1.0 = 1:1).
   */
  price_multiplier: number;
};
