// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from `POST /_vp/credentials/:id/login`.
 */
export type CredentialLoginResponse = { ok: boolean; note: string | null };
