// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialVendor } from "./CredentialVendor.js";
import type { ProviderBalanceSnapshot } from "./ProviderBalanceSnapshot.js";
import type { UsageWindow } from "./UsageWindow.js";

/**
 * A single API key / OAuth account attached to a provider.
 *
 * Supports two mutually exclusive auth modes:
 * - `auth_ref` — resolves via secrets module (keyring, env, literal…)
 * - `oauth_access_token` — token stored directly in SQLite, auto-refreshed via
 *   `oauth_refresh_token` against auth.openai.com.
 *
 * Multiple credentials per provider enable key-pool rotation: each credential
 * gets its own circuit state and rate-limit tracking so a saturated key
 * doesn't block the whole provider.
 */
export type Credential = {
  id: string;
  provider_id: string;
  label: string;
  /**
   * auth_ref mode (keyring:, env:, literal:, …) — no `codex-auth` file paths.
   */
  auth_ref: string | null;
  /**
   * "claude-pro" | "codex-plus" | "codex-pro" | "token" | "payg" | …
   */
  plan_type: string | null;
  notes: string | null;
  enabled: boolean;
  priority: number;
  /**
   * Current OAuth access token (may be near-expiry; auto-refreshed by proxy).
   */
  oauth_access_token: string | null;
  /**
   * Whether a refresh_token is stored (token itself is never returned by API).
   */
  oauth_has_refresh: boolean;
  /**
   * Unix timestamp when the access token expires (null = unknown).
   */
  oauth_expires_at: bigint | null;
  /**
   * User-facing provider group/pool selected on an upstream management platform.
   * Distinct from runtime [`Upstream`]: the gateway combines this credential
   * with each provider endpoint to create upstream units.
   */
  upstream_group: string | null;
  /**
   * Cost multiplier relative to official pricing (default 1.0).
   */
  price_multiplier: number;
  /**
   * Upstream rate-limit headers — updated after every response.
   */
  rl_requests_limit: bigint | null;
  rl_requests_remaining: bigint | null;
  rl_requests_reset_at: bigint | null;
  rl_tokens_limit: bigint | null;
  rl_tokens_remaining: bigint | null;
  rl_tokens_reset_at: bigint | null;
  last_used_at: bigint | null;
  last_error: string | null;
  consecutive_failures: number;
  created_at: bigint;
  updated_at: bigint;
  /**
   * Stable hash for duplicate-import detection (`fp:…`).
   */
  auth_fingerprint: string | null;
  /**
   * From OAuth access JWT when decodable (OpenAI ChatGPT shape, same claims as Codex `parse_chatgpt_jwt_claims`).
   */
  oauth_account_email: string | null;
  /**
   * JWT `sub` or ChatGPT user id when present.
   */
  oauth_account_subject: string | null;
  /**
   * Raw `chatgpt_plan_type` from `https://api.openai.com/auth` in the JWT (e.g. plus, pro); optional UI hint only.
   */
  oauth_chatgpt_plan_slug: string | null;
  /**
   * Model ids fetched with this credential's key (may differ per key).
   */
  remote_models: Array<string>;
  remote_models_fetched_at: bigint | null;
  balance: ProviderBalanceSnapshot | null;
  usage: ProviderBalanceSnapshot | null;
  balance_fetched_at: bigint | null;
  /**
   * Which management platform this credential belongs to.
   */
  upstream_vendor: CredentialVendor | null;
  /**
   * Username for password-based login (NewAPI / Sub2API).
   */
  upstream_username: string | null;
  /**
   * Whether a session token is cached (token itself not returned by API).
   */
  upstream_has_session: boolean;
  /**
   * Unix timestamp when the cached session expires.
   */
  upstream_session_expires_at: bigint | null;
  /**
   * Rolling-window usage snapshots fetched from the upstream platform.
   */
  windows: Array<UsageWindow>;
  /**
   * Why this credential was auto-disabled (e.g. "HTTP 401 from <provider>").
   * Cleared when an operator re-enables the credential.
   */
  disabled_reason: string | null;
  /**
   * Unix seconds when this credential was auto-disabled.
   */
  disabled_at: bigint | null;
};
