// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /_vp/credentials/:id/login`.
 */
export type CredentialLoginRequest = { username: string; password: string };
