// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /_vp/providers/:id/credentials` and `PUT /_vp/credentials/:id`.
 *
 * Set either `auth_ref` (points to a secret) **or** `oauth_access_token` +
 * `oauth_refresh_token` (stored directly in SQLite).  Do not set both.
 */
export type CredentialInput = {
  label: string;
  auth_ref: string | null;
  plan_type: string | null;
  notes: string | null;
  enabled: boolean;
  priority: number;
  oauth_access_token: string | null;
  /**
   * Write-only: stored in DB but never returned in Credential responses.
   */
  oauth_refresh_token: string | null;
  oauth_expires_at: bigint | null;
};
