// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelStat } from "./ModelStat.js";
import type { ProviderStat } from "./ProviderStat.js";

/**
 * Enhanced stats for the dashboard.
 */
export type DashboardStats = {
  /**
   * `hours` query parameter mirrored back for the UI.
   */
  window_hours: bigint;
  /**
   * Human-readable range, e.g. `last 24h`.
   */
  window_label: string;
  /**
   * Aggregates below use this rolling window (same as `hours` query).
   */
  requests_in_window: bigint;
  success_rate_in_window: number;
  input_tokens_in_window: bigint;
  output_tokens_in_window: bigint;
  requests_last_hour: bigint;
  requests_last_24h: bigint;
  success_rate_last_hour: number;
  avg_latency_ms: bigint;
  p95_latency_ms: bigint;
  /**
   * Always last rolling 24h (fixed snapshot card).
   */
  input_tokens_last_24h: bigint;
  output_tokens_last_24h: bigint;
  top_models: Array<ModelStat>;
  per_provider: Array<ProviderStat>;
};
