// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderHealth } from "./ProviderHealth";

/**
 * Summary of health for all providers — returned by `GET /_vp/health/providers`.
 */
export type HealthSummary = {
  providers: Array<ProviderHealth>;
  total_providers: number;
  healthy_providers: number;
};
