// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtraCredential } from "./ExtraCredential.js";
import type { ModelAlias } from "./ModelAlias.js";
import type { ProviderKind } from "./ProviderKind.js";
import type { ProviderProtocol } from "./ProviderProtocol.js";

/**
 * One importable local provider candidate from CC Switch or tool configs.
 */
export type LocalCandidate = {
  client: string;
  name: string;
  kind: ProviderKind;
  base_url: string;
  auth_ref: string | null;
  token_ok: boolean;
  proxy_managed: boolean;
  source_path: string;
  default_aliases: Array<ModelAlias>;
  extra_credentials: Array<ExtraCredential>;
  /**
   * When non-empty, supersedes single `kind` + `base_url` on import.
   */
  protocols: Array<ProviderProtocol>;
};
