// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestLog } from "./RequestLog";

/**
 * Paginated request log envelope returned by `GET /_vp/logs`.
 */
export type LogPage = {
  items: Array<RequestLog>;
  total: bigint;
  limit: bigint;
  offset: bigint;
  has_more: boolean;
};
