// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderHealth } from "./ProviderHealth";
import type { ProviderStat } from "./ProviderStat";

/**
 * Rolling-window gateway stats + cumulative circuit/health for one provider.
 */
export type ProviderHealthSummary = {
  cumulative: ProviderHealth;
  rolling_hours: bigint;
  rolling: ProviderStat | null;
};
