// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialPlanSnapshot } from "./CredentialPlanSnapshot.js";

/**
 * Latest plan snapshot per credential on a ChatGPT Codex provider (`GET /_vp/providers/:id/codex-plan`).
 */
export type ProviderCodexPlanItem = {
  credential_id: string;
  label: string;
  plan: CredentialPlanSnapshot | null;
};
