// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAlias } from "./ModelAlias.js";
import type { ProviderKind } from "./ProviderKind.js";
import type { ProviderProtocol } from "./ProviderProtocol.js";
import type { ProviderSpeedtestResult } from "./ProviderSpeedtestResult.js";
import type { ProviderUpstreamSummary } from "./ProviderUpstreamSummary.js";
import type { Upstream } from "./Upstream.js";

/**
 * A configured upstream provider.
 *
 * `auth_ref` is a string that resolves to a real secret via the `secrets`
 * module of `vibe-core`. Examples: `keyring:anthropic-prod`, `env:OPENAI_API_KEY`.
 */
export type Provider = {
  id: string;
  name: string;
  /**
   * Human-facing provider group, e.g. "Provider A" with HK/SG endpoints below it.
   */
  group_name: string | null;
  /**
   * Optional custom avatar/logo URL for the provider, typically discovered from the upstream site.
   */
  avatar_url: string | null;
  /**
   * Provider is a UI-facing profile/pool. Runtime routing expands it into
   * [`Upstream`] units by crossing endpoints/protocols with credentials.
   */
  upstreams: Array<Upstream>;
  upstream_summary: ProviderUpstreamSummary | null;
  kind: ProviderKind;
  base_url: string;
  /**
   * All wire endpoints for this vendor (Chat + Messages on the same host, etc.).
   */
  protocols: Array<ProviderProtocol>;
  /**
   * Parsed hostname for dedupe and branding (`api.deepseek.com`, …).
   */
  host: string | null;
  auth_ref: string | null;
  enabled: boolean;
  priority: number;
  /**
   * Whether this upstream endpoint itself supports WebSocket transport.
   * `None` means unknown/not measured; the gateway may still accept client WS and bridge to HTTP/SSE.
   */
  supports_websocket: boolean | null;
  /**
   * When true, request model names are passed upstream unchanged unless an explicit alias matches.
   */
  passthrough_mode: boolean;
  /**
   * Latest fetched remote model ids from upstream `/models` (or equivalent), if available.
   */
  remote_models: Array<string>;
  remote_models_fetched_at: bigint | null;
  /**
   * Latest endpoint speed/liveness probe copied from CC Switch's warm-up + measured GET flow.
   */
  last_speedtest: ProviderSpeedtestResult | null;
  /**
   * Maps from a model alias (e.g. "high", "low", or "claude-sonnet") to an
   * upstream model id. Routes are looked up here when forwarding.
   */
  model_aliases: Array<ModelAlias>;
  created_at: bigint;
  updated_at: bigint;
};
