// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderHealthSummary } from "./ProviderHealthSummary.js";

export type ProvidersOverviewHealthChunk = {
  request_id: string;
  rolling_hours: bigint;
  health: Array<ProviderHealthSummary>;
};
