// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderKind = "anthropic" | "openai-chat" | "openai-responses" | "gemini-native";
