// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Credential } from "./Credential.js";

export type ProvidersOverviewCredentialsChunk = {
  request_id: string;
  rolling_hours: bigint;
  provider_id: string;
  credentials: Array<Credential>;
};
