// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderAuthPoolSummary } from "./ProviderAuthPoolSummary.js";

export type ProvidersOverviewPoolsChunk = {
  request_id: string;
  rolling_hours: bigint;
  pools: Array<ProviderAuthPoolSummary>;
};
