// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAlias } from "./ModelAlias.js";
import type { ProviderKind } from "./ProviderKind.js";

/**
 * One upstream wire endpoint for a logical vendor (e.g. DeepSeek Chat + Messages).
 */
export type ProviderProtocol = {
  kind: ProviderKind;
  base_url: string;
  model_aliases: Array<ModelAlias>;
};
