// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderSpeedtestResult = {
  url: string;
  ok: boolean;
  latency_ms: bigint | null;
  status: number | null;
  error: string | null;
  checked_at: bigint;
};
