// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialPoolStatus } from "./CredentialPoolStatus.js";
import type { ProviderKind } from "./ProviderKind.js";

/**
 * Unified auth/key-pool observability view for one provider.
 */
export type ProviderAuthPoolSummary = {
  provider_id: string;
  provider_name: string;
  kind: ProviderKind;
  rolling_hours: bigint;
  total_credentials: bigint;
  enabled_credentials: bigint;
  available_credentials: bigint;
  rate_limited_credentials: bigint;
  open_circuit_credentials: bigint;
  provider_circuit_open_remaining_secs: bigint | null;
  provider_circuit_state: string;
  provider_circuit_open: boolean;
  provider_last_error: string | null;
  credentials: Array<CredentialPoolStatus>;
};
