// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live health record for a provider — returned by `GET /_vp/providers/:id/health`.
 */
export type ProviderHealth = {
  provider_id: string;
  is_healthy: boolean;
  circuit_state: string;
  consecutive_failures: number;
  total_requests: bigint;
  total_successes: bigint;
  total_failures: bigint;
  success_rate: number;
  last_success_at: bigint | null;
  last_failure_at: bigint | null;
  last_error: string | null;
  avg_latency_ms: bigint | null;
  updated_at: bigint;
};
