// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RealtimeProvider = {
  provider_id: string;
  provider_name: string;
  active_requests: number;
  active_output_tokens_per_sec: number;
  active_upstream_bytes_per_sec: number;
  active_downstream_bytes_per_sec: number;
  output_tokens_so_far: bigint;
  upstream_bytes_so_far: bigint;
  client_bytes_so_far: bigint;
};
