// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealtimeProvider } from "./RealtimeProvider";
import type { RealtimeRequest } from "./RealtimeRequest";

export type RealtimeSnapshot = {
  now: bigint;
  active_requests: Array<RealtimeRequest>;
  recent_requests: Array<RealtimeRequest>;
  providers: Array<RealtimeProvider>;
  active_count: number;
  active_output_tokens_per_sec: number;
  active_upstream_bytes_per_sec: number;
  active_downstream_bytes_per_sec: number;
  codex_ws_active: number;
  codex_last_transport: string | null;
};
