// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RealtimeAttempt = {
  attempt_id: string;
  request_id: string;
  attempt_index: number;
  wave_index: number;
  wave_size: number;
  upstream_id: string | null;
  started_at: bigint;
  updated_at: bigint;
  provider_id: string | null;
  credential_id: string | null;
  wire: string | null;
  route_prefix: string | null;
  requested_model: string | null;
  upstream_model: string | null;
  phase: string;
  status_code: number | null;
  upstream_http_status: number | null;
  error: string | null;
  active_output_tokens_per_sec: number | null;
  active_cost_usd_per_hour: number | null;
  active_upstream_bytes_per_sec: number;
  active_downstream_bytes_per_sec: number;
  output_tokens_so_far: bigint;
  upstream_bytes_so_far: bigint;
  client_bytes_so_far: bigint;
  upstream_first_byte_ms: bigint | null;
  client_first_write_ms: bigint | null;
  last_upstream_event_ms: bigint | null;
  last_client_write_ms: bigint | null;
};
