// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAlias } from "./ModelAlias.js";
import type { ProviderBalanceSnapshot } from "./ProviderBalanceSnapshot.js";
import type { RemoteDetectedProtocol } from "./RemoteDetectedProtocol.js";
import type { RemoteProviderCapabilities } from "./RemoteProviderCapabilities.js";

export type RemoteProviderPreview = {
  detected_kind: string;
  detected_base_url: string;
  detected_protocols: Array<RemoteDetectedProtocol>;
  display_name: string;
  avatar_url: string | null;
  note: string;
  passthrough_mode: boolean;
  remote_models: Array<string>;
  model_aliases: Array<ModelAlias>;
  balance: ProviderBalanceSnapshot | null;
  usage: ProviderBalanceSnapshot | null;
  capabilities: RemoteProviderCapabilities;
  fetched_at: bigint;
};
