// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteProviderCapabilities = {
  can_fetch_branding: boolean;
  can_fetch_models: boolean;
  can_fetch_balance: boolean;
  can_fetch_usage: boolean;
};
