// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestLog = {
  id: string;
  started_at: bigint;
  app: string | null;
  provider_id: string | null;
  thread_id: string | null;
  turn_id: string | null;
  trace_id: string | null;
  session_id: string | null;
  requested_model: string | null;
  upstream_model: string | null;
  status_code: number | null;
  error: string | null;
  latency_ms: bigint | null;
  first_token_ms: bigint | null;
  input_tokens: bigint;
  output_tokens: bigint;
  cache_read_tokens: bigint;
  cache_creation_tokens: bigint;
  reasoning_tokens: bigint;
  cache_creation_5m_tokens: bigint;
  cache_creation_1h_tokens: bigint;
  audio_input_tokens: bigint;
  audio_output_tokens: bigint;
  accepted_prediction_tokens: bigint;
  rejected_prediction_tokens: bigint;
  cost_items: string | null;
  /**
   * Stored as a decimal string because we don't want float drift in money.
   */
  estimated_cost_usd: string;
  /**
   * Wire protocol: `anthropic` | `openai-chat` | `openai-responses` | `gemini-native`.
   */
  wire: string | null;
  /**
   * Entry route hint: `codex-v1`, `plain-v1`, `opencode-v1`, …
   */
  route_prefix: string | null;
  credential_id: string | null;
  /**
   * Circuit-breaker key tried for this attempt (`provider_id` or credential uuid).
   */
  cb_key: string | null;
  /**
   * HTTP status from upstream (when distinct from what the client ultimately saw).
   */
  upstream_http_status: number | null;
  /**
   * Upstream JSON/text error body (lossy UTF-8, stored as fully as possible for 4xx and similar cases)。
   */
  upstream_error_preview: string | null;
  /**
   * Optional dedupe key (`x-request-id` + route).
   */
  dedupe_key: string | null;
  /**
   * Client-facing transport used by Vibe: `ws`, `http-sse`, `http`, etc.
   */
  client_transport: string | null;
  /**
   * Sanitized inbound request headers from the client.
   */
  request_headers: string | null;
  /**
   * Inbound HTTP body (gateway perspective, full lossy UTF-8)。
   */
  request_body: string | null;
  /**
   * Upstream response body (non-streaming or locally buffered streaming raw bytes converted to string, not fully truncated)。
   */
  response_body: string | null;
  /**
   * Chat→Responses side: frames sent to the client, such as Codex WS, for comparison with upstream raw Chat SSE in `response_body`.
   */
  client_response_body: string | null;
  stream_kind: string | null;
  stream_terminal_seen: boolean | null;
  stream_end_reason: string | null;
  stream_error_detail: string | null;
  upstream_first_byte_ms: bigint | null;
  client_first_write_ms: bigint | null;
  last_upstream_event_ms: bigint | null;
  last_client_write_ms: bigint | null;
  upstream_chunk_count: bigint;
  upstream_bytes: bigint;
  client_chunk_count: bigint;
  client_bytes: bigint;
  sse_event_count: bigint;
  sse_data_count: bigint;
  sse_comment_count: bigint;
  sse_keepalive_count: bigint;
  sse_done_count: bigint;
  parse_error_count: bigint;
  first_keepalive_ms: bigint | null;
  last_keepalive_ms: bigint | null;
  max_gap_between_upstream_events_ms: bigint | null;
  max_gap_between_data_events_ms: bigint | null;
  keepalive_after_last_data_count: bigint;
  last_data_event_ms: bigint | null;
  bridge_mode: string | null;
  status_injected: boolean;
  terminal_injected: boolean;
  upstream_terminal_type: string | null;
};
