// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestActivity = {
  id: string;
  started_at: bigint;
  app: string | null;
  wire: string | null;
  route_prefix: string | null;
  provider_id: string | null;
  requested_model: string | null;
};
