// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RouteTier } from "./RouteTier.js";

export type Route = {
  id: string;
  name: string;
  match_model: string;
  /**
   * Preferred upstream when this route matches; other matching providers still follow for failover.
   */
  target_provider_id: string | null;
  target_model: string | null;
  tier: RouteTier;
  priority: number;
};
