// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebCompatibility } from "./WebCompatibility.js";

export type Status = {
  version: string;
  web_compatibility: WebCompatibility;
  uptime_secs: bigint;
  port: number;
  providers_total: number;
  providers_enabled: number;
  requests_last_hour: bigint;
  codex_ws_active: number;
  codex_ws_total: number;
  codex_ws_requests_total: number;
  codex_http_responses_total: number;
  codex_last_transport: string | null;
};
