// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpstreamAttemptPhase } from "./UpstreamAttemptPhase.js";

export type UpstreamAttemptActivity = {
  attempt_id: string;
  request_id: string;
  attempt_index: number;
  started_at: bigint;
  phase: UpstreamAttemptPhase;
  provider_id: string | null;
  credential_id: string | null;
  wire: string | null;
  route_prefix: string | null;
  requested_model: string | null;
  upstream_model: string | null;
};
