// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind.js";

/**
 * Runtime upstream candidate synthesized from a UI provider, one endpoint/protocol,
 * and optionally one credential. This is the gateway algorithm's smallest
 * schedulable unit; UI-facing provider records are only templates/pools.
 */
export type Upstream = {
  /**
   * Stable synthetic id: provider + protocol endpoint + credential/provider auth.
   */
  id: string;
  /**
   * UI/provider profile that owns this runtime candidate.
   */
  provider_id: string;
  /**
   * Wire protocol selected for this candidate.
   */
  kind: ProviderKind;
  /**
   * Concrete upstream endpoint used by the gateway.
   */
  base_url: string;
  /**
   * Credential/account chosen for this runtime candidate, if any.
   */
  credential_id: string | null;
  /**
   * Circuit breaker / rate-limit key. Usually credential_id, otherwise provider_id.
   */
  cb_key: string;
  /**
   * Fully resolved availability gate for the algorithm.
   */
  enabled: boolean;
  /**
   * Optional deterministic tie-breaker only; UI priority lives on Provider/Credential.
   */
  priority: number;
};
