// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Group/channel info returned by `GET /_vp/credentials/:id/groups`.
 */
export type UpstreamGroupInfo = {
  id: string;
  name: string;
  description: string | null;
  platform: string | null;
  rate_multiplier: number;
};
