// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpstreamAttemptOutcome } from "./UpstreamAttemptOutcome.js";
import type { UpstreamAttemptPhase } from "./UpstreamAttemptPhase.js";

export type UpstreamAttemptLog = {
  attempt_id: string;
  request_id: string;
  attempt_index: number;
  /**
   * Zero-based scheduler wave for this user request. Attempts in the same wave are concurrent.
   */
  wave_index: number;
  /**
   * Number of upstreams dispatched in this wave.
   */
  wave_size: number;
  /**
   * Minimal runtime upstream id used by gateway scheduling.
   */
  upstream_id: string | null;
  started_at: bigint;
  ended_at: bigint | null;
  provider_id: string | null;
  credential_id: string | null;
  thread_id: string | null;
  turn_id: string | null;
  trace_id: string | null;
  session_id: string | null;
  wire: string | null;
  route_prefix: string | null;
  requested_model: string | null;
  upstream_model: string | null;
  phase: UpstreamAttemptPhase;
  outcome: UpstreamAttemptOutcome;
  status_code: number | null;
  upstream_http_status: number | null;
  error_summary: string | null;
  latency_ms: bigint | null;
  first_token_ms: bigint | null;
  input_tokens: bigint;
  output_tokens: bigint;
  cache_read_tokens: bigint;
  cache_creation_tokens: bigint;
  reasoning_tokens: bigint;
  cache_creation_5m_tokens: bigint;
  cache_creation_1h_tokens: bigint;
  audio_input_tokens: bigint;
  audio_output_tokens: bigint;
  accepted_prediction_tokens: bigint;
  rejected_prediction_tokens: bigint;
  cost_items: string | null;
  /**
   * Stored as decimal USD string for money stability.
   */
  estimated_cost_usd: string;
  upstream_first_byte_ms: bigint | null;
  client_first_write_ms: bigint | null;
  last_upstream_event_ms: bigint | null;
  last_client_write_ms: bigint | null;
  upstream_chunk_count: bigint;
  upstream_bytes: bigint;
  client_chunk_count: bigint;
  client_bytes: bigint;
  sse_event_count: bigint;
  sse_data_count: bigint;
  sse_comment_count: bigint;
  sse_keepalive_count: bigint;
  sse_done_count: bigint;
  parse_error_count: bigint;
  first_keepalive_ms: bigint | null;
  last_keepalive_ms: bigint | null;
  max_gap_between_upstream_events_ms: bigint | null;
  max_gap_between_data_events_ms: bigint | null;
  keepalive_after_last_data_count: bigint;
  last_data_event_ms: bigint | null;
  bridge_mode: string | null;
  status_injected: boolean;
  terminal_injected: boolean;
  upstream_terminal_type: string | null;
  active_upstream_decode_tps_peak: number | null;
  active_downstream_emit_tps_peak: number | null;
  request_headers: string | null;
  request_body: string | null;
  response_headers: string | null;
  response_body: string | null;
};
