// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rolling-window usage snapshot (5 h / 1 d / 7 d).
 */
export type UsageWindow = {
  /**
   * Human-readable label shown in the UI, e.g. "5h", "1d", "7d".
   */
  label: string;
  used_usd: number;
  limit_usd: number | null;
  /**
   * 0.0–100.0 or None when limit unknown.
   */
  used_pct: number | null;
  /**
   * Unix timestamp when the window resets.
   */
  reset_at: bigint | null;
};
