// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageSummary = {
  range: string;
  requests: bigint;
  input_tokens: bigint;
  output_tokens: bigint;
  cache_read_tokens: bigint;
  cache_creation_tokens: bigint;
  reasoning_tokens: bigint;
  cache_creation_5m_tokens: bigint;
  cache_creation_1h_tokens: bigint;
  audio_input_tokens: bigint;
  audio_output_tokens: bigint;
  accepted_prediction_tokens: bigint;
  rejected_prediction_tokens: bigint;
  cost_items: string | null;
  estimated_cost_usd: string;
};
