// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestLog } from "./RequestLog.js";
import type { RequestActivity } from "./RequestActivity.js";
import type { Status } from "./Status.js";

export type WsEvent =
  | { type: "hello"; version: string }
  | ({ type: "status-changed" } & Status)
  | ({ type: "request-started" } & RequestActivity)
  | ({ type: "log-appended" } & RequestLog);
