-- Stream lifecycle diagnostics for SSE / WebSocket disconnect debugging.
ALTER TABLE request_logs ADD COLUMN stream_kind TEXT;
ALTER TABLE request_logs ADD COLUMN stream_terminal_seen INTEGER;
ALTER TABLE request_logs ADD COLUMN stream_end_reason TEXT;
ALTER TABLE request_logs ADD COLUMN stream_error_detail TEXT;
ALTER TABLE request_logs ADD COLUMN upstream_first_byte_ms INTEGER;
ALTER TABLE request_logs ADD COLUMN client_first_write_ms INTEGER;
ALTER TABLE request_logs ADD COLUMN last_upstream_event_ms INTEGER;
ALTER TABLE request_logs ADD COLUMN last_client_write_ms INTEGER;
ALTER TABLE request_logs ADD COLUMN upstream_chunk_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN upstream_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN client_chunk_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN client_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN sse_event_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN sse_data_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN sse_comment_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN sse_keepalive_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN sse_done_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN parse_error_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN first_keepalive_ms INTEGER;
ALTER TABLE request_logs ADD COLUMN last_keepalive_ms INTEGER;
ALTER TABLE request_logs ADD COLUMN max_gap_between_upstream_events_ms INTEGER;
ALTER TABLE request_logs ADD COLUMN max_gap_between_data_events_ms INTEGER;
ALTER TABLE request_logs ADD COLUMN keepalive_after_last_data_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN last_data_event_ms INTEGER;
ALTER TABLE request_logs ADD COLUMN bridge_mode TEXT;
ALTER TABLE request_logs ADD COLUMN status_injected INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN terminal_injected INTEGER NOT NULL DEFAULT 0;
ALTER TABLE request_logs ADD COLUMN upstream_terminal_type TEXT;
