CREATE TABLE upstream_attempt_logs (
    attempt_id                          TEXT PRIMARY KEY,
    request_id                          TEXT NOT NULL,
    attempt_index                       INTEGER NOT NULL,
    started_at                          INTEGER NOT NULL,
    ended_at                            INTEGER,
    provider_id                         TEXT,
    credential_id                       TEXT,
    wire                                TEXT,
    route_prefix                        TEXT,
    requested_model                     TEXT,
    upstream_model                      TEXT,
    phase                               TEXT NOT NULL,
    outcome                             TEXT NOT NULL,
    status_code                         INTEGER,
    upstream_http_status                INTEGER,
    error_summary                       TEXT,
    latency_ms                          INTEGER,
    first_token_ms                      INTEGER,
    input_tokens                        INTEGER NOT NULL DEFAULT 0,
    output_tokens                       INTEGER NOT NULL DEFAULT 0,
    cache_read_tokens                   INTEGER NOT NULL DEFAULT 0,
    cache_creation_tokens               INTEGER NOT NULL DEFAULT 0,
    upstream_first_byte_ms              INTEGER,
    client_first_write_ms               INTEGER,
    last_upstream_event_ms              INTEGER,
    last_client_write_ms                INTEGER,
    upstream_chunk_count                INTEGER NOT NULL DEFAULT 0,
    upstream_bytes                      INTEGER NOT NULL DEFAULT 0,
    client_chunk_count                  INTEGER NOT NULL DEFAULT 0,
    client_bytes                        INTEGER NOT NULL DEFAULT 0,
    sse_event_count                     INTEGER NOT NULL DEFAULT 0,
    sse_data_count                      INTEGER NOT NULL DEFAULT 0,
    sse_comment_count                   INTEGER NOT NULL DEFAULT 0,
    sse_keepalive_count                 INTEGER NOT NULL DEFAULT 0,
    sse_done_count                      INTEGER NOT NULL DEFAULT 0,
    parse_error_count                   INTEGER NOT NULL DEFAULT 0,
    first_keepalive_ms                  INTEGER,
    last_keepalive_ms                   INTEGER,
    max_gap_between_upstream_events_ms  INTEGER,
    max_gap_between_data_events_ms      INTEGER,
    keepalive_after_last_data_count     INTEGER NOT NULL DEFAULT 0,
    last_data_event_ms                  INTEGER,
    bridge_mode                         TEXT,
    status_injected                     INTEGER NOT NULL DEFAULT 0,
    terminal_injected                   INTEGER NOT NULL DEFAULT 0,
    upstream_terminal_type              TEXT,
    active_upstream_decode_tps_peak     REAL,
    active_downstream_emit_tps_peak     REAL,
    FOREIGN KEY (request_id) REFERENCES request_logs(id) ON DELETE CASCADE
);

CREATE INDEX idx_upstream_attempt_logs_request_id
    ON upstream_attempt_logs(request_id, attempt_index);

CREATE INDEX idx_upstream_attempt_logs_provider_started_at
    ON upstream_attempt_logs(provider_id, started_at DESC);
