// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /_vp/providers/:id/credentials`.
 */
export type CredentialInput = {
  label: string;
  auth_ref: string | null;
  plan_type: string | null;
  notes: string | null;
  enabled: boolean;
  priority: number;
};
