// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single API key / account attached to a provider.
 *
 * Multiple credentials per provider enable key-pool rotation: each credential
 * gets its own circuit state and rate-limit tracking so a saturated key
 * doesn't block the whole provider.
 */
export type Credential = {
  id: string;
  provider_id: string;
  label: string;
  auth_ref: string | null;
  /**
   * "claude-pro" | "codex-plus" | "codex-pro" | "token" | "payg" | …
   */
  plan_type: string | null;
  notes: string | null;
  enabled: boolean;
  priority: number;
  /**
   * Upstream rate-limit headers — updated after every response.
   */
  rl_requests_limit: bigint | null;
  rl_requests_remaining: bigint | null;
  rl_requests_reset_at: bigint | null;
  rl_tokens_limit: bigint | null;
  rl_tokens_remaining: bigint | null;
  rl_tokens_reset_at: bigint | null;
  last_used_at: bigint | null;
  last_error: string | null;
  consecutive_failures: number;
  created_at: bigint;
  updated_at: bigint;
};
