// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelStat } from "./ModelStat.js";
import type { ProviderStat } from "./ProviderStat.js";

/**
 * Enhanced stats for the dashboard.
 */
export type DashboardStats = {
  window_hours: bigint;
  window_label: string;
  requests_in_window: bigint;
  success_rate_in_window: number;
  input_tokens_in_window: bigint;
  output_tokens_in_window: bigint;
  requests_last_hour: bigint;
  requests_last_24h: bigint;
  success_rate_last_hour: number;
  avg_latency_ms: bigint;
  p95_latency_ms: bigint;
  input_tokens_last_24h: bigint;
  output_tokens_last_24h: bigint;
  top_models: Array<ModelStat>;
  per_provider: Array<ProviderStat>;
};
