// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelStat = {
  model: string;
  requests: bigint;
  input_tokens: bigint;
  output_tokens: bigint;
};
