// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestLog = {
  id: string;
  started_at: bigint;
  app: string | null;
  provider_id: string | null;
  requested_model: string | null;
  upstream_model: string | null;
  status_code: number | null;
  error: string | null;
  latency_ms: bigint | null;
  first_token_ms: bigint | null;
  input_tokens: bigint;
  output_tokens: bigint;
  cache_read_tokens: bigint;
  cache_creation_tokens: bigint;
  /**
   * Stored as a decimal string because we don't want float drift in money.
   */
  estimated_cost_usd: string;
};
