// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLogLevel } from "./AppLogLevel.js";

export type AppLogEvent = {
  /**
   * Unix timestamp (seconds).
   */
  ts: bigint;
  level: AppLogLevel;
  /**
   * Short category slug: "provider", "credential", "circuit", "system", …
   */
  category: string;
  message: string;
  detail: string | null;
};
