// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `POST /_vp/providers/:id/codex-plan/refresh` or single-credential refresh.
 */
export type CodexPlanRefreshResult = { attempted: number; ok: number; errors: Array<string> };
