// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexAppProcess } from "./CodexAppProcess.js";

export type CodexAppStatus = {
  app_path: string;
  installed: boolean;
  running: boolean;
  main_pid: number | null;
  process_count: number;
  processes: Array<CodexAppProcess>;
};
