// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for previewing or applying Codex App history provider unification.
 */
export type CodexHistoryUnifyInput = {
  provider: string;
  from_providers: Array<string>;
  apply: boolean;
  no_backup: boolean;
  codex_home: string | null;
};
