// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime auth/key-pool status for one credential in a provider pool.
 */
export type CredentialPoolStatus = {
  credential_id: string;
  label: string;
  enabled: boolean;
  /**
   * "oauth" or "auth_ref"
   */
  auth_mode: string;
  circuit_state: string;
  circuit_open: boolean;
  circuit_open_remaining_secs: bigint | null;
  consecutive_failures: number;
  is_rate_limited: boolean;
  rl_requests_remaining: bigint | null;
  rl_requests_reset_at: bigint | null;
  rl_tokens_remaining: bigint | null;
  rl_tokens_reset_at: bigint | null;
  oauth_expires_at: bigint | null;
  last_error: string | null;
  last_used_at: bigint | null;
  /**
   * Rolling-window usage on this credential (hours from ProviderAuthPoolSummary.rolling_hours).
   */
  rolling_requests: bigint;
  rolling_successes: bigint;
  rolling_failures: bigint;
  rolling_avg_latency_ms: bigint | null;
};
