// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CredentialQuotaSource =
  | "response-headers"
  | "codex-plan"
  | "credential-state"
  | "manual";

export type CredentialQuotaState =
  | "available"
  | "warning"
  | "exhausted"
  | "rate-limited"
  | "disabled"
  | "unknown";

export type CredentialQuotaStatus = {
  credential_id: string;
  provider_id: string;
  status: CredentialQuotaState;
  ready: boolean;
  source: CredentialQuotaSource;
  reason: string | null;
  quota_data_json: string | null;
  next_reset_at: bigint | null;
  last_checked_at: bigint | null;
  updated_at: bigint;
};
