// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single API key / OAuth account attached to a provider.
 *
 * Supports two mutually exclusive auth modes:
 *   1. `auth_ref`          — resolves via secrets module (keyring, env, literal…)
 *   2. `oauth_access_token` — token stored directly in SQLite, auto-refreshed via
 *                            `oauth_refresh_token` against auth.openai.com.
 *
 * Multiple credentials per provider enable key-pool rotation: each credential
 * gets its own circuit state and rate-limit tracking so a saturated key
 * doesn't block the whole provider.
 */
export type Credential = {
  id: string;
  provider_id: string;
  label: string;
  /**
   * auth_ref mode (keyring:, env:, literal:, …) — no `codex-auth` file paths.
   */
  auth_ref: string | null;
  /**
   * "claude-pro" | "codex-plus" | "codex-pro" | "token" | "payg" | …
   */
  plan_type: string | null;
  notes: string | null;
  enabled: boolean;
  priority: number;
  /**
   * Current OAuth access token (may be near-expiry; auto-refreshed by proxy).
   */
  oauth_access_token: string | null;
  /**
   * Whether a refresh_token is stored (token itself is never returned by API).
   */
  oauth_has_refresh: boolean;
  /**
   * Unix timestamp when the access token expires (null = unknown).
   */
  oauth_expires_at: bigint | null;
  /**
   * Upstream rate-limit headers — updated after every response.
   */
  rl_requests_limit: bigint | null;
  rl_requests_remaining: bigint | null;
  rl_requests_reset_at: bigint | null;
  rl_tokens_limit: bigint | null;
  rl_tokens_remaining: bigint | null;
  rl_tokens_reset_at: bigint | null;
  last_used_at: bigint | null;
  last_error: string | null;
  consecutive_failures: number;
  created_at: bigint;
  updated_at: bigint;
  /**
   * Stable hash for duplicate-import detection (`fp:…`).
   */
  auth_fingerprint: string | null;
  /**
   * From OAuth access JWT when decodable (OpenAI ChatGPT shape, same claims as Codex `parse_chatgpt_jwt_claims`).
   */
  oauth_account_email: string | null;
  /**
   * JWT `sub` or ChatGPT user id when present.
   */
  oauth_account_subject: string | null;
  /**
   * Raw `chatgpt_plan_type` from `https://api.openai.com/auth` in the JWT (e.g. plus, pro); optional UI hint only.
   */
  oauth_chatgpt_plan_slug: string | null;
};
