// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Latest Codex ChatGPT Plan snapshot parsed from `x-codex-*` response headers.
 */
export type CredentialPlanSnapshot = {
  id: string;
  credential_id: string;
  captured_at: bigint;
  codex_5h_used_percent: number | null;
  codex_7d_used_percent: number | null;
  codex_5h_reset_after_seconds: bigint | null;
  codex_7d_reset_after_seconds: bigint | null;
  codex_primary_used_percent: number | null;
  codex_secondary_used_percent: number | null;
  summary: string | null;
  source: string;
};
