// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which upstream management platform this credential belongs to.
 * Controls login flow, balance API, group listing, and UI hints.
 */
export type CredentialVendor =
  | "generic"
  | "new-api"
  | "sub2-api"
  | "anthropic-payg"
  | "anthropic-plan";
