// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-route forwarding strategy.
 *
 * - `Rotate`: today's default — try expanded picks sequentially, round-robin
 *   counter chooses the starting index, circuit-open picks skipped.
 * - `Race`: fan out the first `Route::fanout_n` credentials concurrently.
 *   Winner = first upstream to emit HTTP 200 + first body byte; losers are
 *   aborted via `CancellationToken`. Costs N× token spend on losers, so this
 *   suits latency-critical short replies, not big agent loops.
 * - `Fallback`: strict sequential mode (no rotation across requests). The
 *   first pick is always tried first; later picks only on failure.
 */
export type ForwardStrategy = "rotate" | "race" | "fallback";
