// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Meta = {
  /**
   * Semver of the running CLI binary.
   */
  cli_version: string;
  /**
   * Gateway protocol epoch (bump when new `/_vp/` endpoints are added).
   */
  protocol_version: number;
  /**
   * Oldest Web UI protocol epoch this gateway can serve.
   */
  min_web_protocol: number;
  /**
   * Canonical URL of the hosted Web UI (GitHub Pages).
   */
  ui_url: string;
};
