// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelPricing = {
  model: string;
  input_per_million_usd: string;
  output_per_million_usd: string;
  cache_read_per_million_usd: string;
  cache_creation_per_million_usd: string;
};
