// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderBalanceSnapshot = {
  currency: string;
  balance: string | null;
  remaining: string | null;
  used: string | null;
  total: string | null;
  period: string | null;
  note: string | null;
};
