// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAlias } from "./ModelAlias.js";
import type { ProviderKind } from "./ProviderKind.js";
import type { ProviderProtocol } from "./ProviderProtocol.js";

/**
 * Body for `POST /_vp/providers` and the patch shape for `PUT`.
 */
export type ProviderInput = {
  name: string;
  group_name: string | null;
  /**
   * Optional custom avatar/logo URL for the provider, typically discovered from the upstream site.
   */
  avatar_url: string | null;
  kind: ProviderKind;
  base_url: string;
  protocols: Array<ProviderProtocol>;
  host: string | null;
  auth_ref: string | null;
  enabled: boolean;
  priority: number;
  supports_websocket: boolean | null;
  passthrough_mode: boolean;
  model_aliases: Array<ModelAlias>;
};
