// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAlias } from "./ModelAlias.js";
import type { ProviderKind } from "./ProviderKind.js";

/**
 * Body for `POST /_vp/providers` and the patch shape for `PUT`.
 */
export type ProviderInput = {
  name: string;
  kind: ProviderKind;
  base_url: string;
  auth_ref: string | null;
  enabled: boolean;
  priority: number;
  model_aliases: Array<ModelAlias>;
};
