// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCodexPlanItem } from "./ProviderCodexPlanItem.js";

export type ProvidersOverviewCodexPlansChunk = {
  request_id: string;
  rolling_hours: bigint;
  provider_id: string;
  codex_plans: Array<ProviderCodexPlanItem>;
};
