// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Upstream } from "./Upstream.js";

/**
 * Aggregated view of runtime upstream units derived from a provider.
 */
export type ProviderUpstreamSummary = {
  provider_id: string;
  total_upstreams: bigint;
  enabled_upstreams: bigint;
  endpoint_count: bigint;
  credential_count: bigint;
  sample_upstreams: Array<Upstream>;
};
