// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider.js";

export type ProvidersOverviewProvidersChunk = {
  request_id: string;
  rolling_hours: bigint;
  providers: Array<Provider>;
};
