// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelAlias } from "./ModelAlias.js";
import type { ProviderKind } from "./ProviderKind.js";

/**
 * A configured upstream provider.
 *
 * `auth_ref` is a string that resolves to a real secret via the `secrets`
 * module of `vibe-core`. Examples: `keyring:anthropic-prod`, `env:OPENAI_API_KEY`.
 */
export type Provider = {
  id: string;
  name: string;
  kind: ProviderKind;
  base_url: string;
  auth_ref: string | null;
  enabled: boolean;
  priority: number;
  /**
   * Maps from a model alias (e.g. "high", "low", or "claude-sonnet") to an
   * upstream model id. Routes are looked up here when forwarding.
   */
  model_aliases: Array<ModelAlias>;
  created_at: bigint;
  updated_at: bigint;
};
