// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Credential } from "./Credential.js";
import type { Provider } from "./Provider.js";
import type { ProviderAuthPoolSummary } from "./ProviderAuthPoolSummary.js";
import type { ProviderCodexPlanItem } from "./ProviderCodexPlanItem.js";
import type { ProviderHealthSummary } from "./ProviderHealthSummary.js";

/**
 * One-shot overview used by the Providers page and websocket delta refresh.
 */
export type ProvidersOverview = {
  rolling_hours: bigint;
  providers: Array<Provider>;
  health: Array<ProviderHealthSummary>;
  pools: Array<ProviderAuthPoolSummary>;
  credentials: { [key in string]?: Array<Credential> };
  codex_plans: { [key in string]?: Array<ProviderCodexPlanItem> };
};
