// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderStat = {
  provider_id: string;
  provider_name: string;
  requests: bigint;
  successes: bigint;
  failures: bigint;
  success_rate: number;
  avg_latency_ms: bigint;
  input_tokens: bigint;
  output_tokens: bigint;
  /**
   * HTTP status breakdown within the same window as other fields.
   */
  err_429: bigint;
  err_503: bigint;
  err_4xx_other: bigint;
  err_5xx_other: bigint;
};
