// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestRuntimeStats = {
  request_id: string;
  attempt_id: string | null;
  provider_id: string | null;
  active_request_tokens_per_sec: number | null;
  active_upstream_decode_tps: number | null;
  active_downstream_emit_tps: number | null;
  active_output_tokens_per_sec: number | null;
  active_upstream_bytes_per_sec: number;
  active_downstream_bytes_per_sec: number;
  active_flow_bytes_per_sec: number;
  output_tokens_so_far: bigint;
  upstream_bytes_so_far: bigint;
  client_bytes_so_far: bigint;
  upstream_first_byte_ms: bigint | null;
  client_first_write_ms: bigint | null;
  attempt_scoped: boolean;
  updated_at: bigint;
};
