// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestLog = {
  id: string;
  started_at: bigint;
  app: string | null;
  provider_id: string | null;
  requested_model: string | null;
  upstream_model: string | null;
  status_code: number | null;
  error: string | null;
  latency_ms: bigint | null;
  first_token_ms: bigint | null;
  input_tokens: bigint;
  output_tokens: bigint;
  cache_read_tokens: bigint;
  cache_creation_tokens: bigint;
  /**
   * Stored as a decimal string because we don't want float drift in money.
   */
  estimated_cost_usd: string;
  /**
   * Wire protocol: `anthropic` | `openai-chat` | `openai-responses` | `gemini-native`.
   */
  wire: string | null;
  /**
   * Entry route hint: `codex-v1`, `plain-v1`, `opencode-v1`, …
   */
  route_prefix: string | null;
  credential_id: string | null;
  /**
   * Circuit-breaker key tried for this attempt (`provider_id` or credential uuid).
   */
  cb_key: string | null;
  /**
   * HTTP status from upstream (when distinct from what the client ultimately saw).
   */
  upstream_http_status: number | null;
  /**
   * Upstream JSON/text error body（4xx 等场景尽量全量 UTF-8 有损存储）。
   */
  upstream_error_preview: string | null;
  /**
   * Optional dedupe key (`x-request-id` + route).
   */
  dedupe_key: string | null;
  /**
   * Inbound HTTP body（网关视角，UTF-8 有损全量）。
   */
  request_body: string | null;
  /**
   * Upstream response body（非流式或本地缓冲的流式原始字节转为字符串，不全量截断）。
   */
  response_body: string | null;
  /**
   * Chat→Responses 侧：发给客户端的帧（如 Codex WS），与 `response_body` 里上游原始 Chat SSE 对照。
   */
  client_response_body: string | null;
};
