// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForwardStrategy } from "./ForwardStrategy.js";
import type { RouteTier } from "./RouteTier.js";

export type RouteInput = {
  name: string;
  match_model: string;
  target_provider_id: string | null;
  target_model: string | null;
  tier: RouteTier;
  priority: number;
  strategy: ForwardStrategy;
  fanout_n: number;
};
