// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Status = {
  version: string;
  uptime_secs: bigint;
  port: number;
  providers_total: number;
  providers_enabled: number;
  requests_last_hour: bigint;
};
