// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageDailyRollup = {
  day: string;
  scope: string;
  provider_id: string;
  credential_id: string;
  upstream_id: string;
  wire: string;
  route_prefix: string;
  upstream_model: string;
  requests: bigint;
  successes: bigint;
  failures: bigint;
  input_tokens: bigint;
  output_tokens: bigint;
  cache_read_tokens: bigint;
  cache_creation_tokens: bigint;
  estimated_cost_usd: string;
  latency_avg_ms: number | null;
  first_token_avg_ms: number | null;
};
