// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageDailyRollup } from "./UsageDailyRollup.js";

export type UsageRollupPage = {
  items: Array<UsageDailyRollup>;
  total: bigint;
  limit: bigint;
  offset: bigint;
  has_more: boolean;
};
